[package]
name = "asyn"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version = "1.10.1", features = ["full"]}
async-std = "1.10.0"
once_cell = "1.8.0"